# Generated by Django 5.0 on 2024-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_driver_sex_driverapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
    ]
