# Generated by Django 5.0 on 2024-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_alter_driver_sex_alter_driverapplication_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("R", "Rejected"),
                    ("A", "Approved"),
                    ("P", "Pending"),
                ],
                default="P",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
    ]
