# Generated by Django 5.0 on 2024-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_driver_rate_count_alter_driver_sex_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="rate_count",
        ),
        migrations.AddField(
            model_name="ride",
            name="rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("P", "Pending"),
                    ("R", "Rejected"),
                ],
                default="P",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("2", "In process"),
                    ("1", "Waiting for client"),
                    ("3", "Finished"),
                ],
                default="1",
                max_length=6,
            ),
        ),
    ]
