# Generated by Django 5.0 on 2024-08-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taxi",
            "0005_remove_driver_rate_count_ride_rate_alter_driver_sex_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["model"]},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"], "verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["user__first_name"]},
        ),
        migrations.AlterModelOptions(
            name="driverapplication",
            options={"ordering": ["status", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="ride",
            options={"ordering": ["status"]},
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("R", "Rejected"),
                    ("P", "Pending"),
                    ("A", "Approved"),
                ],
                default="P",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Waiting for client"),
                    ("2", "In process"),
                    ("3", "Finished"),
                ],
                default="1",
                max_length=6,
            ),
        ),
    ]
