# Generated by Django 5.0 on 2024-08-23 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0005_driverapplication_status_alter_driver_sex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverapplication",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("P", "Pending"),
                    ("R", "Rejected"),
                ],
                default="P",
                max_length=6,
            ),
        ),
    ]
