# Generated by Django 5.0 on 2024-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0006_driverapplication_approved_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverapplication",
            old_name="approved_at",
            new_name="reviewed_at",
        ),
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("R", "Rejected"),
                    ("P", "Pending"),
                ],
                default="P",
                max_length=6,
            ),
        ),
    ]
