# Generated by Django 5.0 on 2024-08-23 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taxi",
            "0007_rename_approved_at_driverapplication_reviewed_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Approved"),
                    ("R", "Rejected"),
                ],
                default="P",
                max_length=6,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_from", models.CharField(max_length=255)),
                ("street_to", models.CharField(max_length=255)),
                ("distance", models.IntegerField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("2", "Paid"),
                            ("1", "Pending"),
                            ("3", "Cancelled"),
                        ],
                        default="1",
                        max_length=6,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxi.city",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
