# Generated by Django 5.0 on 2024-08-23 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taxi",
            "0009_order_is_active_alter_driverapplication_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("R", "Rejected"),
                    ("P", "Pending"),
                ],
                default="P",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("3", "Cancelled"), ("2", "Paid"), ("1", "Pending")],
                default="1",
                max_length=6,
            ),
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("3", "Finished"),
                            ("1", "Waiting for client"),
                            ("2", "In process"),
                        ],
                        default="1",
                        max_length=6,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxi.car",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxi.driver",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxi.order",
                    ),
                ),
            ],
        ),
    ]
