# Generated by Django 5.0 on 2024-08-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0010_alter_driverapplication_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="price_per_meter",
        ),
    ]
