# Generated by Django 5.0 on 2024-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0011_remove_car_price_per_meter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("3", "Cancelled"), ("1", "Pending"), ("2", "Paid")],
                default="1",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("2", "In process"),
                    ("1", "Waiting for client"),
                    ("3", "Finished"),
                ],
                default="1",
                max_length=6,
            ),
        ),
    ]
