# Generated by Django 5.0 on 2024-08-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0012_alter_driver_sex_alter_driverapplication_sex_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("R", "Rejected"),
                    ("A", "Approved"),
                ],
                default="P",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("3", "Finished"),
                    ("1", "Waiting for client"),
                    ("2", "In process"),
                ],
                default="1",
                max_length=6,
            ),
        ),
    ]
