# Generated by Django 5.0 on 2024-08-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0013_remove_order_payment_status_alter_driver_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("2", "In process"),
                    ("3", "Finished"),
                    ("1", "Waiting for client"),
                ],
                default="1",
                max_length=6,
            ),
        ),
    ]
