# Generated by Django 5.0 on 2024-08-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0014_alter_ride_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="taxi.driver",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivers",
                to="taxi.city",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="taxi.city",
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="driverapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("R", "Rejected"),
                    ("P", "Pending"),
                ],
                default="P",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="taxi.city",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides",
                to="taxi.car",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Waiting for client"),
                    ("2", "In process"),
                    ("3", "Finished"),
                ],
                default="1",
                max_length=6,
            ),
        ),
    ]
