# Generated by Django 5.0 on 2024-08-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("taxi", "0014_alter_ride_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="taxi.order",
            ),
            preserve_default=False,
        ),
    ]
