# Generated by Django 5.0 on 2024-08-24 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="taxi.order",
            ),
        ),
    ]
