# Generated by Django 5.0 on 2024-08-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_order"),
        (
            "taxi",
            "0015_alter_car_driver_alter_driver_city_alter_driver_sex_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="taxi.order",
            ),
        ),
    ]
