# Generated by Django 5.0 on 2024-08-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["status"]},
        ),
    ]
