# Generated by Django 5.0 on 2024-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_driver",
            field=models.BooleanField(default=False),
        ),
    ]
